### ISSUE TITLE
Optimización de imagenes

### ISSUE THREAD

**Issue by luchoxx87** [et12webmaster/et12webmaster.github.io#56]
Para esta tarea tenemos que sacar las imágenes del repositorio que **no sean**:

- Icono.
- Banners de las secciones.

Las imágenes ahora las podemos subir a  [este hosting](https://www.imghippo.com/), hay que subirlas y modificar los content para que usen las imagenes recientemente subidas.
Es importante optimizar el tamaño de las imágenes a subir para mejorar la velocidad de descarga de nuestro sitio.

**Comment by luchoxx87** [comment]
Finalmente el hosting que encontramos (https://www.imghippo.com/) no permitía el _hotlink_, por lo que seguiremos investigando

**Comment by VaninaBlas** [comment]
Profesor, este hosting pasa la restricción de la escuela y es gratuito (https://postimages.org/)
